package com.company;


import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Main implements Runnable {

    public static void main(String[] args) {


        List<Integer> randomNumbers = new ArrayList<>();
        RandomThread randomA = new RandomThread("randomA");
        Thread randomA1 = new Thread(randomA);
        randomA1.start();


        RandomThread randomB = new RandomThread("randomB");
        Thread randomB1 = new Thread(randomB);
        randomB1.start();


        RandomThread randomC = new RandomThread("randomC");
        Thread randomC1 = new Thread(randomC);
        randomC1.start();


        RandomThread randomD = new RandomThread("randomD");
        Thread randomD1 = new Thread(randomD);
        randomD1.start();


        RandomThread randomE = new RandomThread("randomE");
        Thread randomE1 = new Thread(randomE);
        randomE1.start();


        try {
            randomA1.join();
            randomB1.join();
            randomC1.join();
            randomD1.join();
            randomE1.join();
        } catch (InterruptedException e) {
            throw new RuntimeException("Interrupt " + e);
        }

        Collections.addAll(randomNumbers, randomA.getRandom(), randomB.getRandom(), randomC.getRandom(), randomD.getRandom(), randomE.getRandom());
        Integer sum = doSum(randomNumbers);
        print(sum);

        Integer sum1 = doSumOfThreads(randomA, randomB);
        Integer sum2 = doSumOfThreads(randomC, randomD, randomE);
        Integer totalSum = sum1 + sum2;
        print(totalSum);

        int sum3 = randomA.getRandom() + randomB.getRandom() + randomC.getRandom() + randomD.getRandom() + randomE.getRandom();
        print(sum3);

    }

    private static Integer doSumOfThreads(RandomThread A, RandomThread B) {
        return A.getRandom() + B.getRandom();
    }

    private static Integer doSumOfThreads(RandomThread C, RandomThread D, RandomThread E) {
        int sum = 0;
        sum += C.getRandom() + D.getRandom() + E.getRandom();
        return sum;
    }


    private static Integer doSum(List<?> randoms) {
        Integer sum = 0;
        for (Object random : randoms) {
            sum += (Integer) random;
        }
        return sum;
    }


    private static void print(Integer sum) {
        System.out.println("Sum of random numbers generated by 5 different Threads is '" + sum + "'");
    }


    @Override
    public void run() {

    }
}
